version: "3.9"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/dbdata:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: mysql


  spring-boot-app:
    image: vovamitsura/testapp-img:latest
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - MAIL_PORT=${MAIL_PORT}
      - USER=${USER}
      - USER_PASSWORD=${USER_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - STRIPE.SECRET=${STRIPE_SECRET}
    volumes:
      - ./data/.m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  dbdata:
    driver: local